[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "arxiv>=2.4.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.135.2",
    "google-genai>=1.69.0",
    "greenlet>=3.3.2",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.48",
]
